#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-mvnfast
Version  : 0.2.8
Release  : 25
URL      : https://cran.r-project.org/src/contrib/mvnfast_0.2.8.tar.gz
Source0  : https://cran.r-project.org/src/contrib/mvnfast_0.2.8.tar.gz
Summary  : Fast Multivariate Normal and Student's t Methods
Group    : Development/Tools
License  : GPL-2.0+ MIT
Requires: R-mvnfast-lib = %{version}-%{release}
Requires: R-mvnfast-license = %{version}-%{release}
Requires: R-BH
Requires: R-Rcpp
Requires: R-RcppArmadillo
BuildRequires : R-BH
BuildRequires : R-Rcpp
BuildRequires : R-RcppArmadillo
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
multivariate normal and Student's t distributions. The main functionalities

%package lib
Summary: lib components for the R-mvnfast package.
Group: Libraries
Requires: R-mvnfast-license = %{version}-%{release}

%description lib
lib components for the R-mvnfast package.


%package license
Summary: license components for the R-mvnfast package.
Group: Default

%description license
license components for the R-mvnfast package.


%prep
%setup -q -n mvnfast
cd %{_builddir}/mvnfast

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1677189086

%install
export SOURCE_DATE_EPOCH=1677189086
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/R-mvnfast
cp %{_builddir}/mvnfast/inst/COPYRIGHTS %{buildroot}/usr/share/package-licenses/R-mvnfast/32af65ce1b0fc5f572d6b247c636c9e871fc07ba || :
export LANG=C.UTF-8
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -ftree-vectorize -mno-vzeroupper -mprefer-vector-width=512  " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/mvnfast/CITATION
/usr/lib64/R/library/mvnfast/COPYRIGHTS
/usr/lib64/R/library/mvnfast/DESCRIPTION
/usr/lib64/R/library/mvnfast/INDEX
/usr/lib64/R/library/mvnfast/Meta/Rd.rds
/usr/lib64/R/library/mvnfast/Meta/features.rds
/usr/lib64/R/library/mvnfast/Meta/hsearch.rds
/usr/lib64/R/library/mvnfast/Meta/links.rds
/usr/lib64/R/library/mvnfast/Meta/nsInfo.rds
/usr/lib64/R/library/mvnfast/Meta/package.rds
/usr/lib64/R/library/mvnfast/Meta/vignette.rds
/usr/lib64/R/library/mvnfast/NAMESPACE
/usr/lib64/R/library/mvnfast/R/mvnfast
/usr/lib64/R/library/mvnfast/R/mvnfast.rdb
/usr/lib64/R/library/mvnfast/R/mvnfast.rdx
/usr/lib64/R/library/mvnfast/doc/index.html
/usr/lib64/R/library/mvnfast/doc/mvnfast.R
/usr/lib64/R/library/mvnfast/doc/mvnfast.Rmd
/usr/lib64/R/library/mvnfast/doc/mvnfast.html
/usr/lib64/R/library/mvnfast/help/AnIndex
/usr/lib64/R/library/mvnfast/help/aliases.rds
/usr/lib64/R/library/mvnfast/help/mvnfast.rdb
/usr/lib64/R/library/mvnfast/help/mvnfast.rdx
/usr/lib64/R/library/mvnfast/help/paths.rds
/usr/lib64/R/library/mvnfast/html/00Index.html
/usr/lib64/R/library/mvnfast/html/R.css
/usr/lib64/R/library/mvnfast/tests/test-all.R
/usr/lib64/R/library/mvnfast/tests/test-dmixt.R
/usr/lib64/R/library/mvnfast/tests/test-dmvn.R
/usr/lib64/R/library/mvnfast/tests/test-dmvt.R
/usr/lib64/R/library/mvnfast/tests/test-ms.R
/usr/lib64/R/library/mvnfast/tests/test-rmixn.R
/usr/lib64/R/library/mvnfast/tests/test-rmixt.R
/usr/lib64/R/library/mvnfast/tests/test-rmvn.R
/usr/lib64/R/library/mvnfast/tests/test-rmvt.R

%files lib
%defattr(-,root,root,-)
/usr/lib64/R/library/mvnfast/libs/mvnfast.so
/usr/lib64/R/library/mvnfast/libs/mvnfast.so.avx2
/usr/lib64/R/library/mvnfast/libs/mvnfast.so.avx512

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/R-mvnfast/32af65ce1b0fc5f572d6b247c636c9e871fc07ba
